---
- hosts: web_servers
  become: true
  tasks:
    - name: Update apt-get(yum in centos) repository
      apt:
        update_cache: yes
      notify:
        - Restart nginx

    - name: Install nginx
      apt:
        name: "nginx"
        state: present
        update_cache: yes
      notify:
        - Restart nginx
    
    - name: Create folder for website
      file: 
        path: "/var/www/{{ website_name }}"
        state: directory
      notify:
        - Restart nginx

    - name: Delete sites-enabled and sites-availble files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/etc/nginx/sites-enabled/default"
        - "/etc/nginx/sites-available/default"
      notify:
        - Restart nginx

    - name: Add webpage to servers
      template:
        src: "index.html.tpl"
        dest: "/var/www/{{ website_name }}/index.html"
      notify:
        - Restart nginx

    - name: Configure nginx with new config file
      template: 
        src: "default.tpl"
        dest: "/etc/nginx/sites-available/{{ website_name }}"
      notify:
        - Restart nginx

    - name: Create symlink for config file
      file:
        src: "/etc/nginx/sites-available/{{ website_name }}"
        dest: "/etc/nginx/sites-enabled/{{ website_name }}"
        state: link
      notify:
        - Restart nginx

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted  





